dist: trusty
language: node_js
node_js:
  - "12"
install:
  - npm ci
  - cp .env.example .env
  - travis_wait 30 npm run build
  - npx ganache-cli > /dev/null &
  - npm run migrate:dev
script:
  - npm run test
  - npm run eslint
  - node src/cli.js test
